# Generated by Django 5.1.1 on 2024-10-31 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('genero_musical', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilRedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SelloDiscografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Hip-Hop', 'Hip-Hop'), ('Clásica', 'Clásica')], max_length=50)),
                ('artistas', models.ManyToManyField(to='musica_app.artista')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musica_app.perfilredessociales'),
        ),
        migrations.AddField(
            model_name='artista',
            name='sello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica_app.sellodiscografico'),
        ),
    ]
